name: Build and test the App

on:
    push:
        branches: ["partie-2/chapitre-2/section-4-fin"]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Running linter
              run: npm run lint

            - name: Run Typecheck
              run: npm run typecheck 

    build_and_test:
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build the app
              run: npm run build

            - name: Testing the app
              run: npm run test 

