name: Build and Test the App

on:
  push:
    branches: ["full-project"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Installing dependencies
        run: npm ci

      - name: Running Linter
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

  build_and_test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Installing dependencies
        run: npm ci

      - name: Building the app
        run: npm run build

      - name: Testing the app
        run: npm run test
