name: A workflow with multiple jobs

on:
    push:
        branches: ["full-project"]

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
    
    second-job:
        needs: first-job
        runs-on: ubuntu-latest

        steps:
            - name: Another job
              run: echo "Second job depends on first one"
